package com.vlin.dao.mappers;

import com.vlin.entity.BuyerInfo;
import com.vlin.entity.BuyerInfoExample;
import java.util.List;

public interface BuyerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    int insert(BuyerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    int insertSelective(BuyerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    List<BuyerInfo> selectByExample(BuyerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    BuyerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    int updateByPrimaryKeySelective(BuyerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_info
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    int updateByPrimaryKey(BuyerInfo record);
}