package com.vlin.entity;

public class BuyerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_info.id
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_info.name
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_info.product
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    private String product;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_info.id
     *
     * @return the value of buyer_info.id
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_info.id
     *
     * @param id the value for buyer_info.id
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_info.name
     *
     * @return the value of buyer_info.name
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_info.name
     *
     * @param name the value for buyer_info.name
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_info.product
     *
     * @return the value of buyer_info.product
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_info.product
     *
     * @param product the value for buyer_info.product
     *
     * @mbggenerated Mon Aug 26 12:28:04 CST 2019
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }
}